# Generated by Django 5.0.14 on 2026-09-14 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '录入'), ('update', '修改'), ('delete', '删除'), ('lock', '锁定'), ('unlock', '解锁')], max_length=10)),
                ('entity_type', models.CharField(max_length=20, verbose_name='实体类型')),
                ('entity_id', models.BigIntegerField(verbose_name='实体ID')),
                ('summary', models.CharField(max_length=300, verbose_name='摘要')),
                ('snapshot', models.JSONField(blank=True, null=True, verbose_name='操作前快照（用于逆操作）')),
                ('undone', models.BooleanField(default=False, verbose_name='已撤销')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '操作留痕',
                'verbose_name_plural': '操作留痕',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ClauseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clause_name', models.CharField(db_index=True, max_length=200, verbose_name='险种或条款名称')),
                ('version_label', models.CharField(blank=True, help_text='如：1999版、批单改后版，可留空', max_length=120, verbose_name='版本标识')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='已删除（误录撤销）')),
            ],
            options={
                'verbose_name': '条款版本',
                'verbose_name_plural': '条款版本',
                'ordering': ['clause_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_no', models.CharField(max_length=64, unique=True, verbose_name='文件编号')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='材料名称')),
                ('kind', models.CharField(choices=[('policy', '保单'), ('renewal', '续期通知'), ('endorsement', '批单'), ('other', '其他材料')], default='other', max_length=16, verbose_name='材料类型')),
                ('scan', models.ImageField(blank=True, null=True, upload_to='scans/%Y/%m/', verbose_name='扫描图')),
                ('issued_earliest', models.DateField(blank=True, null=True, verbose_name='签发日期（最早可能）')),
                ('issued_latest', models.DateField(blank=True, null=True, verbose_name='签发日期（最晚可能）')),
                ('effective_start_earliest', models.DateField(blank=True, null=True, verbose_name='生效起（最早可能）')),
                ('effective_start_latest', models.DateField(blank=True, null=True, verbose_name='生效起（最晚可能）')),
                ('effective_end_earliest', models.DateField(blank=True, null=True, verbose_name='生效止（最早可能）')),
                ('effective_end_latest', models.DateField(blank=True, null=True, verbose_name='生效止（最晚可能）')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='已删除（误录撤销）')),
            ],
            options={
                'verbose_name': '材料',
                'verbose_name_plural': '材料',
                'ordering': ['file_no'],
            },
        ),
        migrations.CreateModel(
            name='ClauseParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_no', models.CharField(help_text='如：第三条、3.2、责任免除第2项', max_length=40, verbose_name='段落号')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='段落标题')),
                ('text', models.TextField(blank=True, verbose_name='段落文本')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='顺序')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='endorsements.clauseversion', verbose_name='所属版本')),
            ],
            options={
                'verbose_name': '条款段落',
                'verbose_name_plural': '条款段落',
                'ordering': ['version_id', 'order', 'id'],
                'unique_together': {('version', 'paragraph_no')},
            },
        ),
        migrations.CreateModel(
            name='QueryConclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_date', models.DateField(db_index=True, verbose_name='指定日期')),
                ('clause_name', models.CharField(blank=True, help_text='空白表示该日期的全量核对', max_length=200, verbose_name='条款名称')),
                ('payload', models.JSONField(verbose_name='结论内容')),
                ('dependency_hash', models.CharField(max_length=64, verbose_name='依赖指纹')),
                ('stale', models.BooleanField(db_index=True, default=False, verbose_name='已过期（需重新生成）')),
                ('stale_reason', models.CharField(blank=True, max_length=300, verbose_name='过期原因')),
            ],
            options={
                'verbose_name': '核对结论缓存',
                'verbose_name_plural': '核对结论缓存',
                'ordering': ['-query_date', '-id'],
                'indexes': [models.Index(fields=['query_date', 'clause_name', 'stale'], name='endorsement_query_d_e8bafa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('replace', '替换（全文）'), ('partial', '局部替换'), ('supplement', '增补'), ('revoke_version', '撤销条款版本'), ('revoke_relation', '撤销一条修改')], max_length=20, verbose_name='关系类型')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='修改说明')),
                ('date_earliest', models.DateField(blank=True, null=True, verbose_name='关系日期（最早可能）')),
                ('date_latest', models.DateField(blank=True, null=True, verbose_name='关系日期（最晚可能）')),
                ('eff_start_earliest', models.DateField(blank=True, null=True, verbose_name='生效起（最早可能）')),
                ('eff_start_latest', models.DateField(blank=True, null=True, verbose_name='生效起（最晚可能）')),
                ('eff_end_earliest', models.DateField(blank=True, null=True, verbose_name='生效止（最早可能）')),
                ('eff_end_latest', models.DateField(blank=True, null=True, verbose_name='生效止（最晚可能）')),
                ('locked', models.BooleanField(default=False, help_text='锁定后不可修改/删除，须先解锁', verbose_name='已确认锁定')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='已删除（误录撤销）')),
                ('affected_paragraphs', models.ManyToManyField(blank=True, related_name='relations', to='endorsements.clauseparagraph', verbose_name='涉及段落（局部替换）')),
                ('from_version', models.ForeignKey(blank=True, help_text='撤销关系可只填目标，不填来源', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_relations', to='endorsements.clauseversion', verbose_name='新版本/来源版本')),
                ('target_relation', models.ForeignKey(blank=True, help_text='仅「撤销一条修改」使用', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_by', to='endorsements.relation', verbose_name='被撤销的关系')),
                ('to_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relations', to='endorsements.clauseversion', verbose_name='被修改的旧版本')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relations', to='endorsements.sourcedocument', verbose_name='依据材料（批单等）')),
            ],
            options={
                'verbose_name': '沿革关系',
                'verbose_name_plural': '沿革关系',
                'ordering': ['date_earliest', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.CharField(db_index=True, max_length=120, verbose_name='挂载目标')),
                ('x', models.FloatField(verbose_name='左（0~1）')),
                ('y', models.FloatField(verbose_name='上（0~1）')),
                ('w', models.FloatField(verbose_name='宽（0~1）')),
                ('h', models.FloatField(verbose_name='高（0~1）')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='框选说明')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='endorsements.sourcedocument', verbose_name='所在扫描件')),
            ],
            options={
                'verbose_name': '依据框选',
                'verbose_name_plural': '依据框选',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='clauseversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clause_versions', to='endorsements.sourcedocument', verbose_name='来源材料'),
        ),
    ]
