# Generated by Django 5.0.14 on 2026-09-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsements', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clauseparagraph',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clauseparagraph',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='已删除（误录撤销）'),
        ),
        migrations.AddIndex(
            model_name='clauseparagraph',
            index=models.Index(fields=['version', 'deleted'], name='endorsement_version_fba7fe_idx'),
        ),
    ]
